server:
  interface: "0.0.0.0"  # Interface to bind to (e.g., 0.0.0.0 for all interfaces)
  port: 8455            # Port number to bind the DNS server to

go:
  application:
    name: amndns

logging:
  file:
    path: "logs/"
    name: "amndns.log"
